name: 'AdaGPT'

# Run the workflow on new issues, pull requests, and comments mentioning @AdaGPT
on:
  workflow_dispatch:
    branches:
      - main
  issues:
    types: [opened]
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

# Allows the workflow to create comments on issues and pull requests
permissions:
  issues: write
  pull-requests: write

jobs:
  adagpt:
    name: AdaGPT comment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check for @AdaGPT mention
        id: check_mention
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "issue_comment" ]]; then
            echo "::set-output name=has_mention::$(echo "$GITHUB_EVENT_PAYLOAD" | jq -r '.comment.body | contains("@AdaGPT")')"
          else
            echo "::set-output name=has_mention::$(echo "$GITHUB_EVENT_PAYLOAD" | jq -r '.body | contains("@AdaGPT")')"
          fi
      - uses: zirkelc/adagpt@v1
        id: adagpt
        name: AdaGPT
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gpt_key: ${{ secrets.GPT_KEY }}
        if: steps.check_mention.outputs.has_mention == 'true'

